version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9100:9000" # S3 API inside -> 9100 outside
      - "9101:9001" # Console inside -> 9101 outside
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - ./minio-data:/data
